services:
  de1:
    image: de
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    networks:
      - backend

  de2:
    image: de
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
    networks:
      - backend

  de3:
    image: de
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - de1
      - de2
      - de3
    networks:
      - backend

networks:
  backend:
    driver: bridge